#!/bin/sh
# Test: https://bkil.gitlab.io/spamisi/

main() {
  local OUT="out"
  mkdir -p "$OUT" || exit 1
  local HTML="$OUT/html"
  local URLBASE="https://osm-gimmisn.vmiklos.hu/"
  local URL="${URLBASE}osm/index.html"

  download "$URL" "$URLBASE" "$HTML"

  {
    get_header "$OUT"
    get_pages "$OUT" "$URL" "$HTML"
    get_footer
  } > "$OUT/index.html"
}

download() {
# TODO: osm/static/stats.json (via stats.ts)
# TODO: osm/static/relations.json (via main.ts)
#    --timestamping
# --reject-regex "^${URLBASE}(osm/(street(-housenumbers)?|filter-for/refcounty)/.*|.*/update-result)$"
# --accept-regex "^${URLBASE}(robots\.txt|osm/(index\.html|static/[^/]+|([^/]+/balatonalmadi/view-[^/]+)|(filter-for|housenumber-stats)/.*|(additional|missing)-[^/]+/[^/]+/view-result))$"

  local URL="$1"
  local URLBASE="$2"
  local HTML="$3"

  wget \
    --directory-prefix="$HTML" \
    --force-directories \
    --no-host-directories \
    --wait=1 \
    --no-parent \
    --recursive \
    --level 4 \
    --adjust-extension \
    --no-clobber \
    --backups=0 \
    --continue \
    --compression=auto \
    --accept-regex "^${URLBASE}(robots\.txt|osm/(index\.html|static/[^/]+|([^/]+/balatonalmadi/view-[^/]+)|(filter-for|housenumber-stats)/.*|(additional|missing)-[^/]+/balatonalmadi/view-result))$" \
    "$URL"
}

get_pages() {
  local OUT="$1"
  local URL="$2"
  local HTML="$3"

  local IDS="$OUT/downloaded-ids.txt"
  local TMP="$OUT/redlinked.html.tmp"
  rm "$IDS" 2>/dev/null

  local MAIN="`echo "$URL" | sed "s~^.*://[^/]*/~$HTML/~"`"

  {
    echo "$MAIN" 1

    find "$HTML" -type f |
    sort |
    fgrep -v "$MAIN" |
    grep -E "^$HTML/osm/((([^/]+/balatonalmadi)|filter-for|housenumber-stats)/|(additional|missing)-[^/]+/[^/]+/view-result)" |
    grep -v "/update-result$"

    # hack: show something during loading and make `get_page_switching_style` work
    echo "$MAIN"
  } |
  while read FILE ISLOADING; do
    local NAME="`echo "$FILE" | sed "s~^$HTML/~~ ; s~/index.html$~~ ; s~\.html$~~ ; s~/~--~g"`"

    echo "$NAME" >> "$IDS"

    get_page "$NAME" "$FILE" "$ISLOADING"
  done > "$TMP"
  local IDREGEX="`sed ":l; N; s~\n~|~g; t l" "$IDS"`"
  sed -r "s~(<a class=\")red(link\" href=\"#($IDREGEX)\")~\1\2~g" "$TMP"
  rm "$TMP"
}

get_page() {
  local NAME="$1"
  local FILE="$2"
  local ISLOADING="$3"

  [ -n "$ISLOADING" ] &&
    local NAME="SPAMISI-LOADING---$NAME"

  local TITLE="`sed -nr "s~^.*<title>(.*)</title>.*$~\1~ ; T e; p; :e" "$FILE"`"
  [ -n "$TITLE" ] || local TITLE="$NAME"

  cat << EOF

<div id="$NAME" class="page">
EOF

  if [ -n "$ISLOADING" ]; then
    echo "<div class=\"title-loading\">$TITLE - LOADING</div>"
  else
    echo "<div class=\"title\">$TITLE - generated by <a href=\"https://github.com/bkil/osm-tooling/blob/master/src/web/spamisi.sh\">spamisi.sh</a></div>"
  fi

  if
    fgrep -q "<!DOCTYPE html>" "$FILE"
  then

  fgrep -v "<!DOCTYPE html>" "$FILE" |
  sed -r "
    s~^.*<body>~~
    s~</body></html>$~~

    s~ id=\"(filter-based-on-position|_daily|_dailytotal|_monthly|_monthlytotal|_topusers|_topcities|_usertotal|_progress)\"~& class=\"nojs-hide\"~g

    s~ id=\"~ id=\"$NAME---~g

    s~(<a href=\"#)([^\"])~\1$NAME---\2~g

    s~(<a href=\"#)(\")~\1$NAME\2~g

    s~(<a href=\"/[^\"]*)/(\")~\1\2~g
    t l
    :l
    s~(<a href=\"/[^\"/]*)/~\1--~g
    t l
    s~(<a)( href=\")/([^\"/]*\")~\1 class=\"redlink\"\2#\3~g
  "

  else
    printf "<pre>"
    cat "$FILE"
    printf "</pre>"
  fi
  
  cat << EOF
</div>
EOF
}

get_header() {
  local OUT="$1"

  cat << EOF
<!DOCTYPE html>
<html lang=""><head>
<link rel="icon" type="image/png" sizes="64x64" href="favicon.ico">
<title>SPA-Misi</title><meta charset="UTF-8" /><style type="text/css">
EOF

  cat "$OUT/html/osm/static/osm.css"

  cat << EOF
.pages > .page {
  display: none;
}

.pages > :first-child {
  display: block;
}

.title {
  color: #fff;
  background-color: #707;
}

.title-loading {
  color: #fff;
  background-color: #770;
}

.redlink {
  color: #900;
}
.link {
  color: #090;
  text-decoration: underline;   
}
.link:hover,
.link:focus {
  color: #090;
  background-color: #efe;
  cursor: pointer;
}
</style>
<meta name="viewport" content="width=device-width, initial-scale=1" />

<style id="style-nojs-hide">
.nojs-hide {
  display: none;
}
</style>

</head><body>
<div class="pages">
EOF
}

get_page_switching_style() {
  cat << EOF
<style type="text/css">
.pages > .page:target ~ .page:last-child, .pages > .page {
  display: none;
}

.pages > :last-child, .pages > .page:target {
  display: block;
}
</style>
EOF
}

get_loading_finished_style() {
  cat << EOF
<style type="text/css">
.title {
  color: #fff;
  background-color: #f00;
}
</style>
EOF
}

get_js() {
  cat << EOF
<script>
document.getElementById("style-nojs-hide").textContent = "";
EOF

  sed -r "
    s~((getElementById|:[{]display:!0,(text|labelString):k)\(\")~\1osm--housenumber-stats--hungary---~g
    s~(uriPrefix=\"/)osm(\")~\1spamisi\2~g
  " "$OUT/html/osm/static/bundle.js"

  cat << EOF
</script>
EOF
}

get_footer() {
  cat << EOF
</div>
EOF

  get_page_switching_style
  get_js
  get_loading_finished_style

  cat << EOF
</body></html>
EOF
}

main "$@"
