#!/bin/sh
# Test: https://bkil.gitlab.io/spamisi/

main() {
  local OUT="out"
  mkdir -p "$OUT" || exit 1
  local HTML="$OUT/html"
  local URLBASE="https://osm-gimmisn.vmiklos.hu/"
  local URL="${URLBASE}osm/index.html"

  download "$URL" "$URLBASE" "$HTML"

  {
    get_header "$OUT"
    get_pages "$OUT" "$URL" "$HTML" "$URLBASE"
    get_footer
  } > "$OUT/index.html"
}

download() {
# TODO: osm/static/stats.json (via stats.ts)
# TODO: osm/static/relations.json (via main.ts)
#    --timestamping
# --reject-regex "^${URLBASE}(osm/(street(-housenumbers)?|filter-for/refcounty)/.*|.*/update-result)$"
# --accept-regex "^${URLBASE}(robots\.txt|osm/(index\.html|static/[^/]+|([^/]+/balatonalmadi/view-[^/]+)|(filter-for|housenumber-stats)/.*|(additional|missing)-[^/]+/[^/]+/view-result))$"

  local URL="$1"
  local URLBASE="$2"
  local HTML="$3"

  wget \
    --directory-prefix="$HTML" \
    --force-directories \
    --no-host-directories \
    --wait=1 \
    --no-parent \
    --recursive \
    --level 4 \
    --adjust-extension \
    --no-clobber \
    --backups=0 \
    --continue \
    --compression=auto \
    --accept-regex "^${URLBASE}(robots\.txt|osm/(index\.html|static/[^/]+|([^/]+/balatonalmadi/view-[^/]+)|(filter-for|housenumber-stats)/.*|(additional|missing)-[^/]+/balatonalmadi/view-result))$" \
    "$URL"
}

get_pages() {
  local OUT="$1"
  local URL="$2"
  local HTML="$3"
  local URLBASE="$4"

  local IDS="$OUT/downloaded-ids.txt"

  local MAIN="`echo "$URL" | sed "s~^.*://[^/]*/~$HTML/~"`"

  get_file_list "$HTML" "$MAIN" |
  sed "s~^$HTML/~~ ; s~/index\.html$~~ ; s~\.html$~~" |
  sort -u > "$IDS"

  local IDREGEX="`sed ":l; N; s~\n~|~g; t l" "$IDS"`"

  get_file_list "$HTML" "$MAIN" |
  {
    local ISLOADING="1"
    while read FILE; do
      get_page "$FILE" "$ISLOADING"
      local ISLOADING=""
    done
  } |
  post_process_page "$IDREGEX" "$URLBASE"
}

get_file_list() {
  local HTML="$1"
  local MAIN="$2"

  # hack: this is shown while the document is being transferred
  echo "$MAIN"

  find "$HTML" -type f |
  sort |
  fgrep -v "$MAIN" |
  grep -E "^$HTML/osm/((([^/]+/balatonalmadi)|filter-for|housenumber-stats)/|(additional|missing)-[^/]+/[^/]+/view-result)" |
  grep -v "/update-result$"

  # hack: this is showed via `get_page_switching_style` after having loaded
  echo "$MAIN"
}

get_page() {
  local FILE="$1"
  local ISLOADING="$2"

  local ENDPOINT="`echo "$FILE" | sed "s~^$HTML/~~ ; s~/index.html$~~ ; s~\.html$~~"`"
  local NAME="`echo "$ENDPOINT" | sed "s~/~--~g"`"

  local IDNAME="$NAME"
  [ -n "$ISLOADING" ] &&
    local IDNAME="SPAMISI-LOADING---$NAME"

  local TITLE="`sed -nr "s~^.*<title>(.*)</title>.*$~\1~ ; T e; p; :e" "$FILE"`"
  [ -n "$TITLE" ] || local TITLE="$IDNAME"

  cat << EOF

<div id="$IDNAME" class="page">
EOF

  if [ -n "$ISLOADING" ]; then
    echo "<div class=\"title-loading\">$TITLE - LOADING</div>"
  else
    echo "<div class=\"title\">$TITLE - generated by <a href=\"https://github.com/bkil/osm-tooling/blob/master/src/web/spamisi.sh\">spamisi.sh</a></div>"
  fi

  if
    fgrep -q "<!DOCTYPE html>" "$FILE"
  then

  fgrep -v "<!DOCTYPE html>" "$FILE" |
  sed -r "
    s~ id=\"~ id=\"$IDNAME---~g

    s~(<a href=\"#)([^\"])~\1$IDNAME---\2~g

    s~(<a href=\"#)(\")~\1$IDNAME\2~g

    s~(<a)( href=\"/${ENDPOINT}/?\")~\1 class=\"selflink\"\2~g
  "

  else
    printf "<pre>"
    cat "$FILE"
    printf "</pre>"
  fi
  
  cat << EOF
</div>
EOF
}

post_process_page() {
  local IDREGEX="$1"
  local URLBASE="$2"

  sed -r "
    s~^.*<body>~~
    s~</body></html>$~~

    s~ id=\"[^\"]*---(filter-based-on-position|_daily|_dailytotal|_monthly|_monthlytotal|_topusers|_topcities|_usertotal|_progress)\"~& class=\"nojs-hide\"~g

    s~(<a( class=\"selflink\")? href=\"/[^\"]*)/(\")~\1\3~g

    s~(<a)( href=\"[^#/][^\"]*\")( target=\"[^\"]*\")?(>)~\1 target=\"_blank\"\2\4~g

    s~(<a)( href=\"/)~\1 class=\"redlink\"\2~g
    s~(<a class=\")red(link\" href=\"/($IDREGEX)\")~\1\2~g
    s~(<a) class=\"redlink\"( href=\")/([^\"]*\")~\1 target=\"_blank\"\2${URLBASE}\3~g

    t l
    :l
    s~(<a class=\"(self)?link\" href=\"/[^\"/]*)/~\1--~g
    t l
    s~(<a class=\"(self)?link\" href=\")/~\1#~g
  "
}

get_header() {
  local OUT="$1"

  cat << EOF
<!DOCTYPE html>
<html lang=""><head>
<link rel="icon" type="image/png" sizes="64x64" href="favicon.ico">
<title>SPA-Misi</title><meta charset="UTF-8" /><style type="text/css">
EOF

  cat "$OUT/html/osm/static/osm.css"

  cat << EOF
.pages > .page {
  display: none;
}

.pages > :first-child {
  display: block;
}

.title {
  color: #fff;
  background-color: #707;
}

.title-loading {
  color: #fff;
  background-color: #770;
}

.link {
  color: #090;
  text-decoration: underline;
}
.link:hover,
.link:focus {
  background-color: #efe;
  cursor: pointer;
}

.selflink {
  color: #fff;
  background-color: #000;
  text-decoration: none;
}
</style>
<meta name="viewport" content="width=device-width, initial-scale=1" />

<style id="style-nojs-hide">
.nojs-hide {
  display: none;
}
</style>

</head><body>
<div class="pages">
EOF
}

get_page_switching_style() {
  cat << EOF
<style type="text/css">
.pages > .page:target ~ .page:last-child, .pages > .page {
  display: none;
}

.pages > :last-child, .pages > .page:target {
  display: block;
}
</style>
EOF
}

get_loading_finished_style() {
  cat << EOF
<style type="text/css">
.title {
  color: #fff;
  background-color: #f00;
}
</style>
EOF
}

get_js() {
  cat << EOF
<script>
document.getElementById("style-nojs-hide").textContent = "";
EOF

  sed -r "
    s~((getElementById|:[{]display:!0,(text|labelString):k)\(\")~\1osm--housenumber-stats--hungary---~g
    s~(uriPrefix=\"/)osm(\")~\1spamisi\2~g
  " "$OUT/html/osm/static/bundle.js"

  cat << EOF
</script>
EOF
}

get_footer() {
  cat << EOF
</div>
EOF

  get_page_switching_style
  get_js
  get_loading_finished_style

  cat << EOF
</body></html>
EOF
}

main "$@"
